#! /bin/sh

#sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         2
#bspc config window_gap          12

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#panel &
# lemonbar
#lemonbuddy_terminate noconfirm
#lemonbuddy_wrapper top &

# lowers lemonbar to the bottom of the screen
# a fix for fullscreen games, video, etc

#~/bin/lowerlemonbar

bspc config border_width        1
bspc config window_gap          30
bspc config top_padding         5
bspc config left_padding        8
bspc config right_padding       8
bspc config bottom_padding      15

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	false
bspc config history_aware_focus  	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	false
bspc config click_to_focus 			false
bspc config adaptive raise 			true

bspc config center_pseudo_tiled  true


bspc config normal_border_color "#131313"
bspc config focused_border_color "#57c7ff"
bspc config presel_feedback_color "#57c7ff"

bspc monitor -d 1 2 3 4 5 6 7 8

bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating

#feh --bg-center ~/Downloads/MK1gCx9.jpg &
feh --bg-scale ~/Downloads/SPACE.jpg &
#lemonbuddy_wrapper top &
$HOME/.config/polybar/launch.sh &
compton --config "$HOME/.config/compton.conf" -b &
systemctl --user start mopidy
