#!/bin/bash

# store current mouse location
mouse_location="$(xdotool getmouselocation --shell)"
while IFS= read -r line; do
    declare "$line"
done <<< "$mouse_location"

# store resolution of current monitor
current_monitor_resolution="$(get_focused_monitor_resolution)"
while IFS= read -r line; do
    declare "$line"
done <<< "$current_monitor_resolution"

# mark currently focused window
i3-msg mark "bwmenu-mark"

# move mouse to upper-left of screen
warpd --move '1 1'

# Disable clipboard manager temporarily
copyq disable

# call bwmenu and pass along all given parameters
bwmenu "$@"

# Enable clipboard manager
copyq enable

# move mouse back to where it was before calling bwmenu
# (modulo resolution of current monitor, since warpd is relative to current monitor)
warpd --move "$((X % WIDTH)) $((Y % HEIGHT))"

# focus on window with mark
i3-msg '[con_mark="bwmenu-mark"] focus'

# remove mark
i3-msg unmark "bwmenu-mark"
