#!/bin/bash

# Try to toggle playing status
if ! playerctl play-pause; then
    /usr/bin/notify-send -u low "No players found"
    exit 1
fi

# Get song info
ARTIST=$(playerctl metadata xesam:albumArtist)
ALBUM=$(playerctl metadata xesam:album)
SONG=$(playerctl metadata xesam:title)

if [[ $ARTIST = "" ]]; then
    ARTIST=$(playerctl metadata xesam:artist)
    DETAILS=$ARTIST
else
    DETAILS="$ARTIST - $ALBUM"
fi

# Get album art URL
IMAGE_URL="$(playerctl metadata mpris:artUrl)"

if [[ $IMAGE_URL = "file://"* ]]; then
    IMAGE_PATH=$(echo "$IMAGE_URL" | sd 'file://' '')
    cp "$IMAGE_PATH" /tmp/album_icon.jpg
else
    # Download image
    wget -O /tmp/album_icon.jpg "$IMAGE_URL"
fi

STATUS=$(playerctl status)
if [[ $STATUS = "Playing" ]]; then
    STATUS=""
else
    STATUS=""
fi

# Show notification
/usr/bin/notify-send -u low "$SONG $STATUS" "$DETAILS" --icon /tmp/album_icon.jpg
