#!/bin/bash

log() {
    tput setaf 1; >&2 echo "### $1 ###"; tput sgr 0
}

PLAYERS=$(playerctl -l)
log "players: '$PLAYERS'"

if echo "$PLAYERS" | grep -w "Sonixd"; then
    log "Sonixd running"
    PLAYER="Sonixd"
elif echo "$PLAYERS" | grep -w "spotify"; then
    log "spotify running"
    PLAYER="spotify"
else
    PLAYER="${PLAYERS[0]}"
fi

log "Selected player: $PLAYER"

# Try to toggle playing status
if ! playerctl -p "$PLAYER" play-pause; then
    /usr/bin/notify-send -u low "No players found"
    exit 1
fi

# Get song info
ARTIST=$(playerctl -p "$PLAYER" metadata xesam:artist)
ALBUM_ARTIST=$(playerctl -p "$PLAYER" metadata xesam:albumArtist)
ALBUM=$(playerctl -p "$PLAYER" metadata xesam:album)
SONG=$(playerctl -p "$PLAYER" metadata xesam:title)

if [[ $ARTIST != "$ALBUM_ARTIST" ]]; then
    DETAILS="$ARTIST ($ALBUM_ARTIST)"
else
    DETAILS=$ARTIST
fi

if [[ $ALBUM != "" ]]; then
    DETAILS="$DETAILS - $ALBUM"
fi

log "Details: $DETAILS"

# Get album art URL
IMAGE_URL="$(playerctl -p "$PLAYER" metadata mpris:artUrl)"

if [[ $IMAGE_URL = "file://"* ]]; then
    IMAGE_PATH=$(echo "$IMAGE_URL" | sd 'file://' '')
    log "Image path: $IMAGE_PATH"
    cp "$IMAGE_PATH" /tmp/album_icon.jpg
else
    # Download image
    wget -O /tmp/album_icon.jpg "$IMAGE_URL"
    log "Image URL: $IMAGE_URL"
fi

STATUS=$(playerctl -p "$PLAYER" status)
if [[ $STATUS = "Playing" ]]; then
    STATUS="󰐊"
else
    STATUS="󰏤"
fi

if [[ $(playerctl -p "$PLAYER" shuffle) = "On" ]]; then
    STATUS="${STATUS} 󰒟"
fi

if [[ $(playerctl -p "$PLAYER" loop) = "Playlist" ]]; then
    STATUS="${STATUS} 󱞲"
elif [[ $(playerctl -p "$PLAYER" loop) = "Track" ]]; then
    STATUS="${STATUS} 󱦙"
fi

log "Status: $STATUS"

# Show notification
log "Dunst: $(pidof dunst)"
/usr/bin/notify-send -u low "$SONG / $STATUS" "$DETAILS" --icon /tmp/album_icon.jpg
