#!/bin/bash

ROFI_FONT=${1}

# Check for dependencies
INSTALLED_ERROR="has to be installed. Exiting."
command -v sed >/dev/null  2>&1 || { echo >&2 "'sed' $INSTALLED_ERROR"; exit 1; }
command -v find >/dev/null 2>&1 || { echo >&2 "'find' $INSTALLED_ERROR"; exit 1; }
command -v rofi >/dev/null 2>&1 || { echo >&2 "'rofi' $INSTALLED_ERROR"; exit 1; }

OBSIDIAN_DIR="/home/leon/Sync/Obsidian"
VAULT_NAME="Notes"

# Use rofi to get the path to the desired file
SELECTED=$(
    # find all files in vault, which are not hidden, with last edit datetime
    find "$OBSIDIAN_DIR/$VAULT_NAME/" -type f -not -path '*/.*' -printf "%T+\t%p\n" | \
    # sort lines in reverse (last edited on top)
    sort -r | \
    # remove date from lines
    sed -e "s|^\w.*\t||" | \
    # Remove base dir from paths
    sed -e "s|$OBSIDIAN_DIR/$VAULT_NAME/||" | \
    # Open list in rofi
    rofi -i -dmenu -p "obsidian" -sort -sorting-method fzf -matching fuzzy -width 1000 -font "$ROFI_FONT" -theme ~/.cache/wal/colors-rofi.rasi -monitor -1
)

# Escape ampersands (&) in filenames
SELECTED=$(echo "$SELECTED" | sd '&' '%26')

# Exit if no file was selected
if [[ "$SELECTED" == "" ]]
then
    exit 0
fi

# Open selected file in Obsidian, send process to background
# `openmode=true` ensures that the file is opened in a new tab.
# More info: https://vinzent03.github.io/obsidian-advanced-uri/
xdg-open "obsidian://advanced-uri?vault=$VAULT_NAME&filepath=$SELECTED&openmode=true" &

# ensure shell does not own Obsidian process
disown "$!"

# exit
exit 0
