#!/bin/bash

if [ "$EUID" != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

INTERFACE=$(ip route | rg default | sd '.* dev (.*?) .*' '$1')

echo "Default interface: $INTERFACE"

ip route add 192.168.1.0/24 via 192.168.3.1 dev "$INTERFACE"
ip route add 192.168.2.0/24 via 192.168.3.1 dev "$INTERFACE"
ip route add 192.168.4.0/24 via 192.168.3.1 dev "$INTERFACE"
