#!/bin/bash

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/leon/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/leon/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/leon/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/leon/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PURE_PROMPT_SYMBOL="(anaconda) %F{white}%F{blue}%f"

conda activate env
